### PR TITLE
images

### PR DESCRIPTION
**Pull request by kwalpratham**

### CODE REVIEW

**Review by codetronaut — COMMENTED** [review]
@kwalpratham please update the repository with relevant images. Most of the images that have been uploaded are way outdated. Please arrange images of workshops and events conducted by DSC.

**Review by codetronaut — CHANGES_REQUESTED** [review]
@kwalpratham  Please note

**Comment by aayushigupt** [comment]
Images should be relevant they are outdated. You should make them more impressive.

**Review by aayushigupt — COMMENTED** [review]
Images should be relevant as they are outdated. You should collect appropriate images.

**Review by dewanshrawat15 — CHANGES_REQUESTED** [review]
@kwalpratham, @codetronaut and @aayushigupt are right. These images won't work for the website.

**Comment by dewanshrawat15** [comment]
@kwalpratham whats the update on this?

**Pull request closed without merging**
